### ISSUE TITLE
Regrading to "NeRF_Representing_Scenes_as_Neural_Radiance_Fields_for_View_Synthesis"

### ISSUE THREAD

**Issue by chenmingxiang110** [MaximeVandegar/Papers-in-100-Lines-of-Code#2]
Hi Max,

Thanks very much for your detailed tutorial on Youtube. But I have one thing pretty confused about. Taking the training dataset as an example, where the shape is 16,000,000 by 9, I see the first three numbers are the ray_origins, the mid three are the ray_directions, and the last three are the RGB colors. I am wondering how the ray origins and ray directions are computed. The problem may be tedious, but I think it would very helpful if it could be included in the video or the code.

**Comment by MaximeVandegar** [comment]
Hi @chenmingxiang110,

Thank you for your suggestion. The aim of this repository is to provide i) short, and ii) self-contained implementations. I did not include the ray computation in order to keep the code short, but I agree it alters the self-contained criterion.

I think the ray computation can be incorporated in 15-20 lines of code, I will try to add them in the near future, thank you.

In case you need more details about the ray computation, here is a [nice script](https://github.com/kwea123/nerf_pl/blob/master/datasets/blender.py), or[ my Udemy course](https://www.udemy.com/course/neural-radiance-fields-nerf/?referralCode=DD33817D57404AF048DF) where we discuss it in details.

**Comment by chenmingxiang110** [comment]
Thank you very much for your reply:-)
